apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
data:
  CRYSTAL_URL: "http://{{ .Release.Name }}-crystal.{{ .Release.Namespace }}.svc.cluster.local/crystal"
  NODEJS_URL: "http://{{ .Release.Name }}-nodejs.{{ .Release.Namespace }}.svc.cluster.local/"
